### ISSUE TITLE
Query List

### ISSUE THREAD

**Issue by CristianoRC** [CristianoRC/DotCEP#10]
Utilizar a biblioteca Spartacus como micro ORM para fazer a busca de cache e localidades via QueryList e não mais via DataTable.

**Comment by CristianoRC** [comment]
Foi  utilizado o método Spartacus.Utils.Convert.DataTableToList para desenvolver a nova solução do projeto.

**Comment by wind39** [comment]
Cristiano, é possível utilizar o método QueryList<T>? Este método é mais rápido que utilizar os dois métodos Query e DataTableToList<T>.

**Comment by CristianoRC** [comment]
Sim é possível, eu utilizei o conversor, pois eu utilizo um método para fara fazer todas as requisições da classe, mas não sabia que o QueryList era mais rápido, vou reformular a classe para poder ter uma mais performance na biblioteca. Obrigado pela dica.

**Comment by wind39** [comment]
Só para explicar melhor sobre a performance:

- `Query`: Executa a consulta no banco e obtém os dados alimentando um `DataTable`;
- `QueryList<T>`: Executa a consulta no banco e obtém os dados alimentando um `List<T>` diretamente;
- `DataTableToList<T>`: Converte um `DataTable` para um `List<T>`.

Se você precisa dos dados na forma de `DataTable`, use `Query`. Se você precisa dos dados em `List<T>`, use `QueryList<T>`.

**Comment by CristianoRC** [comment]
Foi feita a troca do conversor por QueryList, muito obrigado pela dica @wind39.

**Comment by wind39** [comment]
Parabéns, a **DotCEP** está ficando cada vez melhor! :+1:
