### ISSUE TITLE
Criar cache local

### ISSUE THREAD

**Issue by wind39** [CristianoRC/DotCEP#4]
Cristiano,

Primeiramente gostaria de parabenizar sua iniciativa e seu trabalho nessa biblioteca, realmente é bem útil.

No Reddit, o usuário **jvframework** deu uma sugestão interessante: que você implemente uma cache local para reduzir o tempo de resposta. Vou tentar explicar uma abordagem pra isso funcionar. A ideia é ter um banco de dados _dotcep.db_ local inicialmente vazio. Quando o programa chama, por exemplo:

```
enderecoBase = Consultas.ObterEnderecoCompleto("70160-900");
```

A resposta deverá ter as seguintes informações:

```
CEP: 70160-900
Logradouro: Praça dos Três Poderes
Localidade: Brasília
Bairro: Zona Cívico-Administrativa
UF: DF
ibge: 5300108
Complemento:
Gia:
Unidade:
```

Beleza, na primeira vez a cache está vazia e precisa buscar da Internet. Mas, assim que retornar, o próprio método _ObterEnderecoCompleto_ deve armazenar em uma tabela _cache_ no banco _dotcep.db_ as seguintes informações:

```
Data/Hora: 20161028 155800 (por exemplo)
Metodo: ObterEnderecoCompleto
Parametro: 70160-900
Retorno: (aqui você coloca uma stringona contendo todo o retorno do Via CEP).
```

Se caso a aplicação fizer uma nova chamada ao método _ObterEnderecoCompleto_, primeiro ele verifica se existe na cache uma linha com o mesmo parâmetro. Se existir, ele deve olhar a Data/Hora e verificar se é mais antigo do que, por exemplo, 1 semana ou 1 mês (endereços não mudam com tanta frequencia). Se for mais antigo, ele deve excluir o registro, consultar o site do Via CEP de novo e reinserir o registro atualizado na cache.

Mas se caso o registro existir na cache e não for tão antigo, você pode usar a informação que já está na cache. Nesse caso vai ficar mil vezes mais rápido pro usuário e não precisará usar a conexão com a Internet.

O que achou da ideia? Estou disponível para conversarmos se você quiser. Abraço!

**Comment by CristianoRC** [comment]
Ótima ideia, vou pensar em uma maneira legal em desenvolver isso.

**Comment by CristianoRC** [comment]
Fiz alguns testes na consulta de Endereço por CEP e o resulta foram bem legais, e o resultado da pesquisa da web e o de deletar os resultados vão depender muito da conexão.

```
WEB : 1,998286s  /  2,183947s
Banco : 0,46547s  /  0,425365s
Deletar: 2,56527s  /  2,270873
```

Só falta corrigir a parte de caminho do banco, na hora de criar uma conexão devo passar o caminho, @wind39  você conhece um modo de fazer isso que fincione no Linux/Windows?

Função mencionada assima: `Cache.ObterCaminhoBanco()`

**Comment by wind39** [comment]
Legal! Veja se a PR #5 ajuda.

**Comment by wind39** [comment]
Você implementou a cache para todos os métodos da DotCEP?

**Comment by CristianoRC** [comment]
Implememtei para os métodos que fazem pesquisa por CEP, os métodos que retornam uma lista de endereço eu não implementei, pois estou pensando em uma maneira legal de fazer isso, pois não sei se sepraro os endereços da Lista JSON um por um ou se coloco o retorno de uma vez só.

**Comment by wind39** [comment]
Talvez precise de uma tabela cache para manter um id, a data/hora, o nome do método e o(s) parâmetro(s), e outra tabela cache_data, para manter os dados. Essa tabela teria uma FK para a tabela cache, e poderia ter vários dados para uma mesma chamada do método.

**Comment by CristianoRC** [comment]
Foi implementado o sistema de cache por consultas, e foram criados índices nas tabelas de consulta e cache do banco.
