### ISSUE TITLE
Erro de DLL Sqlite3

### ISSUE THREAD

**Issue by jmmccota** [CristianoRC/DotCEP#6]
Quando efetuo uma consulta, esta me retornando erro na DLL Sqlite3 , falando que ela não pode ser encontrada pelo spartacus, como devo proceder?

**Comment by CristianoRC** [comment]
Olá @jmmccota  tudo bem? então cara, queria saber se você chegou a colocar os arquivos da pasta DotCEP, que foi no diretório do seu projeto na pasta do executável. E também qual o seu sistema operacional.
Da uma olhada na Wiki sobre a instalação, lá tem mais detalhado, mas se continuar dando erro, retorna aqui e informa, que eu do uma olhada mais a fundo no seu problema.
https://github.com/CristianoRC/DotCEP/wiki

**Comment by jmmccota** [comment]
Olá @CristianoRC tudo bem, e com vc?

Eu estou desenvolvendo uma aplicação web Aspnet MVC5(.Net 4.6.1), desenvolvendo ela em Windows 10 usando VS2015.

Fiz a instalação seguindo minuciosamente a wiki, porem não obtive sucesso com a busca através da biblioteca.

Obrigado.

**Comment by wind39** [comment]
Olá, @jmmccota , tudo certo?

A raiz de um projeto desktop é a pasta `bin/Release` ou `bin/Debug`, mas a raiz de um projeto ASP.NET é diferente: é a própria pasta do projeto, onde estão os arquivos `.aspx` e `.cs`, o arquivo `web.config`, etc.

Sugiro que você coloque a pasta Cache da biblioteca `DotCep` na pasta raiz do teu projeto. Quanto às bibliotecas nativas (libsqlite3.so, sqlite3.def e sqlite3.dll), eu acredito que elas precisam estar na pasta `bin`, junto com a `Spartacus.dll` e `DotCep.dll` depois de compilado o teu projeto ASP.NET.

**Comment by jmmccota** [comment]
Olá @wind39 tudo, e com vc?

Não teria como eu fazer isso automaticamente? Teria que ficar copiando mesmo?

Visto que quando vou publicar, ele deleta tudo que esta dentro da pasta /bin/

Outra questão, não teria como encapsular essa biblioteca toda dentro de um projeto só?

**Comment by wind39** [comment]
@jmmccota , podemos pensar numa forma de implementar uma tratativa na biblioteca `DotCep` (mais precisamente, na linha que define o caminho para o banco, no fonte [Ferramentas.cs](https://github.com/CristianoRC/DotCEP/blob/master/DotCep/DotCep/Ferramentas.cs#L9) para identificar se está em um projeto web ou desktop e tratar caminhos de formas diferentes.

Outra ideia seria ter um pacote Nuget diferente para projetos web, talvez chamado `DotCepWeb`.

Enquanto isso, você poderia tentar alterar seu processo de publicação? Ao rodar Clean num projeto, os arquivos que você colocou manualmente na pasta bin não são apagados. Talvez chamar um comando extra na tua publicação, talvez.

Sim, é possível mesclar `Spartacus.dll` e `DotCep.dll` em uma única biblioteca. Mas isso não resolveria teu problema, porque ainda seria necessário ter um arquivo `Cache/Cache.db` e as bibliotecas nativas, tudo separado.

**Comment by jmmccota** [comment]
@wind39 Mesmo seguindo suas orientações, ocorreu o erro. Veja na imagem:
https://dl.dropboxusercontent.com/u/7073854/ErrorDll.png

**Comment by wind39** [comment]
Legal, @jmmccota , você conseguiria enviar um printscreen mostrando tua hierarquia de pastas?

**Comment by jmmccota** [comment]
@wind39 o projeto de cima é o MVC, como não havia o dotcep nele, eu instalei, e copiei as pastas e arquivos para os locais que vc me sugeriu https://dl.dropboxusercontent.com/u/7073854/HierarquiaDll.png

**Comment by wind39** [comment]
@jmmccota , da forma como o `DotCep` funciona hoje, você precisa colocar a pasta `Cache` na raiz, e não a pasta `DotCep`.

**Comment by jmmccota** [comment]
@wind39 aparentemente funcionou. Muito obrigado. Se lançar uma versão web gostaria de testar.

**Comment by wind39** [comment]
Agradeço sua disposição, @jmmccota ! Na sequencia, eu e o @CristianoRC vamos estudar a possibilidade de implementar um pacote Nuget específico para web.
